# Scaffolding generated by Casein v5.0.0.0

module Casein
  class BlogPostsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Blog posts'
  		@blog_posts = BlogPost.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View blog post'
      @blog_post = BlogPost.friendly.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new blog post'
    	@blog_post = BlogPost.new
    end

    def create
      @blog_post = BlogPost.new blog_post_params
    
      if @blog_post.save
        flash[:notice] = 'Blog post created'
        redirect_to casein_blog_posts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new blog post'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update blog post'
      
      @blog_post = BlogPost.friendly.find params[:id]
      @blog_post.slug = nil
    
      if @blog_post.update_attributes blog_post_params
        flash[:notice] = 'Blog post has been updated'
        redirect_to casein_blog_posts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this blog post'
        render :action => :show
      end
    end
 
    def destroy
      @blog_post = BlogPost.friendly.find params[:id]

      @blog_post.destroy
      flash[:notice] = 'Blog post has been deleted'
      redirect_to casein_blog_posts_path
    end
  
    private
      
      def blog_post_params
        params.require(:blog_post).permit(:title, :content, :blog_category_id, :date_posted, :published)
      end

  end
end