# Scaffolding generated by Casein v.4.0.0

module Casein
  class SectionsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Sections'
  		@sections = Section.paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View section'
      @section = Section.find params[:id]
    end
 
    def new
      @casein_page_title = 'Add a new section'
    	@section = Section.new
    end

    def create
      @section = Section.new section_params
    
      if @section.save
        flash[:notice] = 'Section created'
        redirect_to casein_sections_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new section'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update section'
      
      @section = Section.find params[:id]
    
      if @section.update_attributes section_params
        flash[:notice] = 'Section has been updated'
        redirect_to casein_sections_path
      else
        flash.now[:warning] = 'There were problems when trying to update this section'
        render :action => :show
      end
    end
 
    def destroy
      @section = Section.find params[:id]

      @section.destroy
      flash[:notice] = 'Section has been deleted'
      redirect_to casein_sections_path
    end
  
    private
      
      def section_params
        params.require(:section).permit(:name, :description, :section_id, :order)
      end

  end
end