source 'https://rubygems.org'
ruby '2.6.0'

gem 'activeadmin', '~> 1.4'
gem 'annotate', '~> 2.7'
gem 'bootstrap-sass', '~> 3.4'
gem 'coderay', '~> 1.1'
gem 'coffee-rails', '~> 4.2'
gem 'devise', "~> 4.7"
gem 'dotenv-rails', '~> 2.7'
gem 'email_validator', '~> 1.6'
gem 'friendly_id', '~> 5.2'
gem 'jquery-rails', '~> 4.3'
gem 'kaminari', '~> 0.17'
gem 'letter_opener', '~> 1.7'
gem 'mailchimp-api', '~> 2.0', require: 'mailchimp'
gem 'pessimize', '~> 0.4'
gem 'pg', '~> 0.21'
gem 'quiet_assets', '~> 1.1'
gem 'rails', '~> 4.2'
gem 'redcarpet', '~> 3.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '~> 3.2'
gem 'unicorn', '~> 5.5'

group :development do
  gem 'better_errors', '~> 2.5'
  gem 'binding_of_caller', '~> 0.8'
  gem 'brakeman', '~> 3.7'
  gem 'byebug', '~> 8.2'
  gem 'mina', '~> 0.3'
  gem 'mina-nginx', '~> 0.0', require: false
  gem 'rack-mini-profiler', '~> 0.10'
  gem 'rubocop', '~> 0.74'
  gem 'faker'
end
