source 'https://rubygems.org'
ruby '2.2.3'

gem 'activeadmin', '~> 1.2'
gem 'annotate', '~> 2.7'
gem 'bootstrap-sass', '~> 3.4'
gem 'coderay', '~> 1.1'
gem 'coffee-rails', '~> 4.2'
gem 'devise', '~> 3.5'
gem 'dotenv-rails', '~> 2.2'
gem 'email_validator', '~> 1.6'
gem 'friendly_id', '~> 5.2'
gem 'jquery-rails', '~> 4.3'
gem 'kaminari', '~> 0.17'
gem 'letter_opener', '~> 1.6'
gem 'mailchimp-api', '~> 2.0', require: 'mailchimp'
gem 'pessimize', '~> 0.3'
gem 'pg', '~> 0.21'
gem 'quiet_assets', '~> 1.1'
gem 'rails', '~> 4.2'
gem 'redcarpet', '~> 3.4'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '~> 3.2'
gem 'unicorn', '~> 5.4'

group :development do
  gem 'better_errors', '~> 2.4'
  gem 'binding_of_caller', '~> 0.8'
  gem 'brakeman', '~> 3.7'
  gem 'byebug', '~> 8.2'
  gem 'mina', '0.3.8'
  gem 'mina-nginx', '0.0.1', require: false
  gem 'rack-mini-profiler', '~> 0.10'
  gem 'rubocop', '~> 0.52'
end
